### ISSUE TITLE
回生別総括/一回生総括 誤字修正

### ISSUE THREAD

**Issue by CityBear3** [ritscc/soukai-2020-2#149]
https://github.com/ritscc/soukai-2020-2/blob/c7a776f81c84cdd1131588137c18a825a13e0fa7/src/soukatsu/1kai.tex#L26
の
`技術力が向上や，`
を
`技術力の向上し，`
に修正してください

**Comment by 1uf3** [comment]
`会員の技術力の向上`　よりも　`会員の技術力が向上`　の方が文的に正しいと思うのですかどうでしょうか？

**Comment by 1uf3** [comment]
変更するとしたら`会員の技術力が向上し，新しい知識を得ることができた．`でどうでしょうか

**Comment by CityBear3** [comment]
それでお願いします
